-- Insert sample data into DEPARTMENTS table
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES (1, 'HR');
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES (2, 'IT');
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES (3, 'Finance');

-- Insert sample data into EMPLOYEES table
INSERT INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT_ID) VALUES (1, 'John Doe', 1);
INSERT INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT_ID) VALUES (2, 'Jane Smith', 2);
INSERT INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT_ID) VALUES (3, 'Alice Johnson', 3);

-- Insert sample data into PROJECTS table
INSERT INTO PROJECTS (PROJECT_ID, PROJECT_NAME, START_DATE, END_DATE) VALUES (1, 'Project A', '2024-01-01', '2024-06-30');
INSERT INTO PROJECTS (PROJECT_ID, PROJECT_NAME, START_DATE, END_DATE) VALUES (2, 'Project B', '2024-02-01', '2024-07-31');

-- Insert sample data into EMPLOYEE_PROJECTS table
INSERT INTO EMPLOYEE_PROJECTS (EMPLOYEE_ID, PROJECT_ID) VALUES (1, 1);
INSERT INTO EMPLOYEE_PROJECTS (EMPLOYEE_ID, PROJECT_ID) VALUES (2, 2);
INSERT INTO EMPLOYEE_PROJECTS (EMPLOYEE_ID, PROJECT_ID) VALUES (3, 1);
